GET http://localhost:4000/user-api/getUsers

###
GET http://localhost:4000/user-api/getUser/123

###
POST http://localhost:4000/user-api/createUser
Content-Type: application/json

{
    "id":9010,
    "name":"ramu",
    "password":"ramu123",
    "email":"ramu@gmail.com",
    "age":30
}

###
PUT http://localhost:4000/user-api/updateUser
Content-Type: application/json

{
    "id":122,
    "name":"Vikram",
    "email":"vikram@gmail.com",
    "age":28
}

###
DELETE http://localhost:4000/user-api/removeUser/9010

###
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
    "userId":"124",
    "password":"sunny"
}
